name: sugarblood
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  open_file: ^3.3.1
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  intl: ^0.20.2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0
  http: ^1.3.0
  file_picker: ^10.1.2
  path_provider: ^2.0.15
  syncfusion_flutter_charts: 29.1.40
  flutter_pdfview: ^1.2.2
  open_filex: 4.7.0
  syncfusion_flutter_pdfviewer: ^29.1.40
  youtube_player_flutter: ^9.1.1
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/diabetes_illustration.png
    - assets/doctor_team.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
